### ISSUE TITLE
Demo not working on Safari 9.1

### ISSUE THREAD

**Issue by lukerohde** [volmer/bootsy#204]
The demo at http://bootsy-demo.herokuapp.com isn't working on my Safari 9.1.  

I haven't had time to look into it but thought I'd report it before I forget.

TypeError: rangy.getSelection is not a function. (In 'rangy.getSelection(this.doc.defaultView||this.doc.parentWindow)', 'rangy.getSelection' is undefined)

http://bootsy-demo.herokuapp.com/assets/application-8e6e18fbf1181921449dc5c63a191e304fe8044dfc96193d56cd7c3275630def.js:6924
![bootsy_trouble](https://cloud.githubusercontent.com/assets/1400034/15033319/bfbc961e-12ac-11e6-823a-152a3249084c.png)

**Comment by volmer** [comment]
Just tested with Safari 9.1 and the demo works fine. Are you sure you don't have an extension messing around with it?

**Comment by lukerohde** [comment]
You guessed it!  JSONView 1.7 breaks it.  Hmm...
