### ISSUE TITLE
Support version Rails 3.2

### ISSUE THREAD

**Issue by adrianoresende** [volmer/bootsy#145]
My project work with Rails 3.2 but...
```
➜  project git:(master) ✗ rake sunspot:reindex
rake aborted!
NoMethodError: undefined method `before_action' for Bootsy::ImagesController:Class
...
```
I know this is for Rails 4 but changing `before_action` for `before_filter` is solved with Rails 3.2.

**Comment by volmer** [comment]
Hi there,

I know it looks tempting to fix these backwards incompatibilities but it gets trickier to offer support to old versions over time. Feel free to fork the project and change it according to your needs :wink:
